### ISSUE TITLE
No module named "Queue"

### ISSUE THREAD

**Issue by Hatom1K** [CharlesBlonde/libpurecoollink#16]
I have an issue when i try this API.

When i launch my .py file, i have this error:

```
root@jeedomVM:/var/www/html/plugins/dyson# python script.py 
Traceback (most recent call last):
  File "script.py", line 1, in <module>
    from libpurecoollink.dyson import DysonAccount
  File "/usr/local/lib/python2.7/dist-packages/libpurecoollink/dyson.py", line 10, in <module>
    from .dyson_360_eye import Dyson360Eye
  File "/usr/local/lib/python2.7/dist-packages/libpurecoollink/dyson_360_eye.py", line 10, in <module>
    from .dyson_device import DysonDevice, NetworkDevice, DEFAULT_PORT
  File "/usr/local/lib/python2.7/dist-packages/libpurecoollink/dyson_device.py", line 5, in <module>
    from queue import Queue
ImportError: No module named queue
```

Thanks

**Comment by exking** [comment]
use python3

**Comment by Hatom1K** [comment]
Ok done, it's okay.
But now i find nothing on my dyson account::
```
root@jeedomVM:/var/www/html/plugins/dyson# python3 script.py 
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:845: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
Traceback (most recent call last):
  File "script.py", line 21, in <module>
    connected = devices[0].connect("192.168.1.14")
IndexError: list index out of range
```
i can intereact with my fan by the android app .. :/

**Comment by TheLion** [comment]
I have the same "list index out of range" error with my DP04 and using Python3.

**Comment by exking** [comment]
New TP04 and DP04 machines are only supported with [PR#15](https://github.com/CharlesBlonde/libpurecoollink/pull/15) which @CharlesBlonde is yet to merge...

**Comment by TheLion** [comment]
OK, thanks. Will keep an eye out for that.
