### ISSUE TITLE
Can't log into Dyson account

### ISSUE THREAD

**Issue by xxKeoxx** [CharlesBlonde/libpurecoollink#18]
Is this still supported?  I can't seem to get a successful login.  I know my ID and PW are correct because I can log in with them just fine on the dyson site.

**Comment by xxKeoxx** [comment]
Never mind.  The instructions say you need to pass the language code, but it's actually country code.

**Comment by tshamilton** [comment]
Thanks for that, it's the difference here between "EN" and "AU" (Australia).

Meanwhile, I'm logging in OK, it's identifying my fan, but I'm not getting it to do anything, and it's throwing InsecureRequestWarning when I run my test script (cut and pasted from the main site). Are you having any luck?

**Comment by trevorludgate** [comment]
Try adding this to your script:
import urllib3
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

Let me know! :)

**Comment by tshamilton** [comment]
Thanks trevor! that's certainly got rid of the message, now to work out why it's not responding to commands...

**Comment by LauraFlem** [comment]
Hi there, having some issues myself with set up. I think I can correctly log onto my dyson account but when I try to list the devices registered to the account it outputs nothing, even though I have a dyson pure cool fan registered online. Has anyone come across this? I was also getting the InsecureRequestWarning message but now that I added the suggestion made above to the script it outputs nothing. Any help would be greatly appreciated :)

**Comment by exking** [comment]
> Hi there, having some issues myself with set up. I think I can correctly log onto my dyson account but when I try to list the devices registered to the account it outputs nothing

Please look at https://github.com/CharlesBlonde/libpurecoollink/issues/14 as it adds support for newer devices.

**Comment by LauraFlem** [comment]
Thanks very much exking!

**Comment by LauraFlem** [comment]
> Please look at #14 as it adds support for newer devices.

@exking Did you have any issues manually connecting your device? However I have downloaded the branch made to support newer devices and can now see my fan but it wont connect.  I get the following output:

`Traceback (most recent call last):

  File "<ipython-input-21-e1fa0a35465e>", line 18, in <module>
    connected = devices[0].connect("192.168.1.2")

  File "C:\Users\elec\Anaconda3\lib\site-packages\libpurecoollink\dyson_pure_cool_link.py", line 148, in connect
    return self._mqtt_connect()

  File "C:\Users\elec\Anaconda3\lib\site-packages\libpurecoollink\dyson_pure_cool_link.py", line 157, in _mqtt_connect
    self._network_device.port)

  File "C:\Users\elec\Anaconda3\lib\site-packages\paho\mqtt\client.py", line 839, in connect
    return self.reconnect()

  File "C:\Users\elec\Anaconda3\lib\site-packages\paho\mqtt\client.py", line 962, in reconnect
    sock = socket.create_connection((self._host, self._port), source_address=(self._bind_address, 0))

  File "C:\Users\elec\Anaconda3\lib\socket.py", line 712, in create_connection
    raise err

  File "C:\Users\elec\Anaconda3\lib\socket.py", line 703, in create_connection
    sock.connect(sa)

TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond`

Auto connect also will not work.

**Comment by exking** [comment]
@LauraFlem mine connects just fine

**Comment by georgeglessner** [comment]
@LauraFlem Try to use [nmap](https://nmap.org/) to find correct IP of your device `nmap -p 1883 192.168.0.1/24 --open` change the `192.168.0.1` to whatever your network address is.

**Comment by jagribble** [comment]
Has anyone been able to connect to it recently? I'm getting a 404 response.

**Comment by theho** [comment]
> Has anyone been able to connect to it recently? I'm getting a 404 response.

I am getting 404 as well.
Is anyone else experiencing the same issue?

**Comment by exking** [comment]
switch to [this](https://github.com/etheralm/libpurecool)
